### ISSUE TITLE
f_nndistance.so: undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by pedrogarciafreitas** [mauriceqch/pcc_attr_folding#1]
I followed the recommended steps to build the Chamfer distance and I got the followed warnings:

```/opt/conda/Anaconda3/lib/python3.7/site-packages/tensorflow_core/include/unsupported/Eigen/CXX11/../../../Eigen/src/Core/MathFunctions.h(1317): warning: calling a constexpr __host__ function("imag") from a __host__ __device__ function("abs") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this```

After added the `--expt-relaxed-constexpr` flag to nvcc and `-D_GLIBCXX_USE_CXX11_ABI=0` to gcc, the script ran with no error. However, `src/ops/chamfer_dist_test.py` generates the following error:

```
Traceback (most recent call last):
  File "chamfer_dist_test.py", line 3, in <module>
    from chamfer_dist import chamfer_dist
  File "~/pcc_attr_folding/src/ops/chamfer_dist.py", line 2, in <module>
    from nn_distance import nn_distance, nn_distance2
  File "~/pcc_attr_folding/src/ops/nn_distance/__init__.py", line 1, in <module>
    from .nn_distance import nn_distance
  File "~/pcc_attr_folding/src/ops/nn_distance/nn_distance.py", line 9, in <module>
    os.path.join(os.path.dirname(__file__), 'tf_nndistance.so'))
  File "/opt/conda/Anaconda3/envs/py36_tensorflow-compression/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ~/pcc_attr_folding/src/ops/nn_distance/tf_nndistance.so: undefined symbol: __cudaRegisterFatBinaryEnd
```

Apparently, there is no linking problems with `tf_nndistance.so`. 

```
$ ldd nn_distance/tf_nndistance.so
	linux-vdso.so.1 (0x00007fffff3ae000)
	libtensorflow_framework.so.1 => /opt/conda/Anaconda3/lib/python3.7/site-packages/tensorflow_core/libtensorflow_framework.so.1 (0x00007f3cb559c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3cb51c8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3cb4fb0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3cb4bbf000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3cb49b7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3cb4798000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3cb4594000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3cb41f6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3cb7492000)
```

I am using a Conda environment with Python 3.6.10, cudatoolkit 10.0.130, and tensorflow-gpu 1.15.0. 

Can you help me? Thanks!

**Comment by mauriceqch** [comment]
Hi @pedrogarciafreitas,

Thank you for your interest.

It seems that the CUDA library is not being linked to `tf_nndistance.so`.
Could you check `$LD_LIBRARY_PATH` ?
```
echo $LD_LIBRARY_PATH
```
The output should include the CUDA libraries as below:
```
:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
```

If `$LD_LIBRARY_PATH` is correct, could you check the library itself ?
Here is an example below for my setup:
```
readelf -sW /usr/local/cuda/lib64/libcudart.so.10.0.130 | grep FatBinaryEnd
```
which gives the following result:
```
# 390: 0000000000010ab0    37 FUNC    GLOBAL DEFAULT   11 __cudaRegisterFatBinaryEnd@@libcudart.so.10.0
```

**Comment by pedrogarciafreitas** [comment]
Hi @mauriceqch 

Thank you for the rapid response. 

`$LD_LIBRARY_PATH` is

```:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/SSD/programs/kakadu:/opt/conda/Anaconda3/lib/python3.7/site-packages/tensorflow_core```

Actually, the environment is able to run other Tensorflow and CUDA programs. 

The command `readelf -sW /usr/local/cuda/lib64/libcudart.so.10.1.168 | grep FatBinaryEnd` gives

```
 389: 0000000000010fb0    37 FUNC    GLOBAL DEFAULT   11 __cudaRegisterFatBinaryEnd@@libcudart.so.10.1
```

**Comment by mauriceqch** [comment]
The error could be because you have CUDA 10.1 instead of CUDA 10.0 as specified in the tested build configurations (https://www.tensorflow.org/install/source#gpu).

Could you also check the following ? (change the environment name "py36" to yours)
```
strings -a ~/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/libtensorflow_framework.so | grep "GCC: ("
g++ --version
nvcc  --version
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
python --version
python -c "import tensorflow as tf; print(tf.__version__); print(tf.sysconfig.get_include()); print(tf.sysconfig.get_lib())"
```

On my environment, I have:
```
GCC: (Ubuntu 7.5.0-3ubuntu1~19.10) 7.5.0
g++ (Ubuntu 7.5.0-3ubuntu1~19.10) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 2
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
Python 3.6.9 :: Anaconda, Inc.
1.15.0
/home/quachmau/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core/include
/home/quachmau/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow_core
```

**Comment by pedrogarciafreitas** [comment]
Hi @mauriceqch 

Aparently, the error was caused by gcc version. The default gcc version was 9.3.0. I changed it to 7.5.0 via ` sudo update-alternatives --config gcc`, re-ran compile.sh, and then the `nn_distance_test.py` worked fine. 

Thank you for your assistance.

**Comment by mauriceqch** [comment]
Hi @pedrogarciafreitas 

Happy to know that you resolved the issue !
